# Generated by Django 4.2.25 on 2025-11-21 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0002_alter_event_description_alter_event_event_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitiondetail',
            name='announcement_date',
        ),
        migrations.RemoveField(
            model_name='jobannouncement',
            name='company',
        ),
        migrations.AddField(
            model_name='competitiondetail',
            name='winner_picture',
            field=models.ImageField(blank=True, null=True, upload_to='winner_picture'),
        ),
        migrations.AlterField(
            model_name='jobannouncement',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('internship', 'Internship'), ('contract', 'Contract')], default='full_time', max_length=50),
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
