# Generated by Django 4.2.25 on 2025-11-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0004_alter_news_content_alter_news_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='identityNo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='post',
        ),
    ]
